# Generated by Django 4.2.9 on 2024-01-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosagrarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='DatosAgrarios',
        ),
        migrations.RenameField(
            model_name='datosagrarios',
            old_name='año_precio',
            new_name='anyo_precio',
        ),
    ]
